import { Project, CameraPreset } from '@/types';

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'house-001',
    name: 'Modern Pavilion Villa',
    clientName: 'Aura Living Developments',
    description: 'Single-storey contemporary villa featuring open-plan living, panoramic floor-to-ceiling glazing, and seamless indoor-outdoor terrace living.',
    modelUrl: '/models/modern-villa.glb',
    thumbnailUrl: '/models/villa-thumb.png',
    status: 'published',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-22T14:30:00Z',
    viewsCount: 342,
    savedConfigsCount: 28,
    zones: [
      {
        id: 'wall_ext',
        name: 'Exterior Walls',
        category: 'wall',
        meshNames: ['Wall_Exterior_Main', 'Wall_Exterior_Accent'],
        defaultMaterialId: 'wall-pure-white',
        description: 'Main exterior facade surfaces and entry accent column.',
      },
      {
        id: 'wall_interior',
        name: 'Interior Walls',
        category: 'wall',
        meshNames: ['Wall_Interior'],
        defaultMaterialId: 'wall-warm-cream',
        description: 'Living room partitions and bedroom dividing walls.',
      },
      {
        id: 'floor_living',
        name: 'Living Room Flooring',
        category: 'floor',
        meshNames: ['Floor_Living'],
        defaultMaterialId: 'floor-oak-natural',
        description: 'Main living room and open kitchen dining floor.',
      },
      {
        id: 'floor_bedroom',
        name: 'Bedroom Flooring',
        category: 'floor',
        meshNames: ['Floor_Bedroom'],
        defaultMaterialId: 'floor-herringbone',
        description: 'Master bedroom suite floor area.',
      },
      {
        id: 'floor_bathroom',
        name: 'Bathroom Floor Tiles',
        category: 'bathroom',
        meshNames: ['Floor_Bathroom'],
        defaultMaterialId: 'floor-carrara-marble',
        description: 'Master ensuite bathroom floor tiles.',
      },
      {
        id: 'wall_bathroom',
        name: 'Bathroom Wall Tiles',
        category: 'bathroom',
        meshNames: ['Wall_Bathroom'],
        defaultMaterialId: 'tile-white-subway',
        description: 'Full height ceramic tiles in bathroom shower zone.',
      },
      {
        id: 'roof_main',
        name: 'Floating Roof Canopy',
        category: 'roof',
        meshNames: ['Roof_Main'],
        defaultMaterialId: 'roof-zinc-charcoal',
        description: 'Architectural cantilevered roof plane.',
      },
      {
        id: 'door_entrance',
        name: 'Entrance Door',
        category: 'door',
        meshNames: ['Door_Entrance'],
        defaultMaterialId: 'door-teak-wood',
        description: 'Main architectural entry door pivot.',
      },
      {
        id: 'deck_patio',
        name: 'Outdoor Patio Decking',
        category: 'floor',
        meshNames: ['Deck_Patio'],
        defaultMaterialId: 'floor-oak-natural',
        description: 'Sun terrace deck adjacent to living area.',
      },
    ],
  },
  {
    id: 'studio-002',
    name: 'Nordic Minimalist Studio',
    clientName: 'Krona Architectural Group',
    description: 'Compact 85m² architectural guest pavilion with polished microcement surfaces, dark accents, and private Japanese bath garden.',
    modelUrl: '/models/minimalist-studio.glb',
    thumbnailUrl: '/models/studio-thumb.png',
    status: 'published',
    createdAt: '2026-03-10T12:00:00Z',
    updatedAt: '2026-03-20T16:00:00Z',
    viewsCount: 189,
    savedConfigsCount: 14,
    zones: [
      {
        id: 'wall_ext',
        name: 'Studio Exterior Facade',
        category: 'wall',
        meshNames: ['Wall_Exterior_Main', 'Wall_Exterior_Accent'],
        defaultMaterialId: 'wall-nordic-beige',
        description: 'Main insulated perimeter walls and timber slats.',
      },
      {
        id: 'floor_living',
        name: 'Studio Main Floor',
        category: 'floor',
        meshNames: ['Floor_Living'],
        defaultMaterialId: 'floor-polished-concrete',
        description: 'Seamless continuous microcement studio floor.',
      },
      {
        id: 'floor_bathroom',
        name: 'Ensuite Stone Surfaces',
        category: 'bathroom',
        meshNames: ['Floor_Bathroom', 'Wall_Bathroom'],
        defaultMaterialId: 'tile-travertine-stone',
        description: 'Honed travertine floor and wet room partitions.',
      },
      {
        id: 'roof_main',
        name: 'Flat Parapet Roof',
        category: 'roof',
        meshNames: ['Roof_Main'],
        defaultMaterialId: 'roof-slate-black',
        description: 'Minimalist flat roof with concealed drainage.',
      },
      {
        id: 'door_entrance',
        name: 'Pivot Entrance Door',
        category: 'door',
        meshNames: ['Door_Entrance'],
        defaultMaterialId: 'door-black-aluminum',
        description: 'Black anodized architectural entrance door.',
      },
    ],
  },
];

export const CAMERA_PRESETS: CameraPreset[] = [
  {
    id: 'exterior',
    name: 'Exterior Hero',
    iconName: 'Eye',
    position: [12, 8, 14],
    target: [0, 1.5, 0],
    description: 'Overview showing front facade, roofline and outdoor terrace',
  },
  {
    id: 'living',
    name: 'Living Space',
    iconName: 'Sofa',
    position: [-1, 2.8, 4.5],
    target: [-2.5, 1.2, 0.5],
    description: 'Inside the main living area looking across oak floors and windows',
  },
  {
    id: 'bathroom',
    name: 'Bathroom Suite',
    iconName: 'Bath',
    position: [5.5, 2.5, -1.5],
    target: [3.8, 1.8, -3.8],
    description: 'Close inspection of bathroom wall tiles and stone flooring',
  },
  {
    id: 'bedroom',
    name: 'Bedroom Wing',
    iconName: 'Bed',
    position: [-2.0, 2.6, -1.8],
    target: [-3.8, 1.2, -3.8],
    description: 'Master bedroom area with herringbone parquet flooring',
  },
  {
    id: 'facade',
    name: 'Front Facade',
    iconName: 'Sun',
    position: [2, 3.5, 12],
    target: [0, 1.8, 2],
    description: 'Direct elevation view of windows, doors and exterior finish',
  },
  {
    id: 'top',
    name: 'Plan View',
    iconName: 'Grid',
    position: [0, 18, 0.01],
    target: [0, 0, 0],
    description: 'Architectural top-down layout floor plan',
  },
];
