import { MaterialOption, MaterialCategory } from '@/types';

export const MATERIAL_CATEGORIES: { id: MaterialCategory; label: string; icon: string }[] = [
  { id: 'wall', label: 'Walls', icon: 'Paintbrush' },
  { id: 'floor', label: 'Floors', icon: 'LayoutGrid' },
  { id: 'bathroom', label: 'Bathroom & Tiles', icon: 'Sparkles' },
  { id: 'roof', label: 'Roofing', icon: 'Home' },
  { id: 'door', label: 'Doors & Frames', icon: 'DoorOpen' },
  { id: 'exterior', label: 'Exterior Facade', icon: 'Building' },
];

export const MATERIAL_LIBRARY: MaterialOption[] = [
  // --- WALL MATERIALS (COLORS) ---
  {
    id: 'wall-pure-white',
    name: 'Pure Architectural White',
    category: 'wall',
    type: 'color',
    color: '#F8F9FA',
    roughness: 0.9,
    metalness: 0.0,
    finish: 'matte',
    description: 'Crisp, bright, light-reflective architectural chalk white.',
    tag: 'Popular',
  },
  {
    id: 'wall-warm-cream',
    name: 'Warm Scandinavian Cream',
    category: 'wall',
    type: 'color',
    color: '#EDE8DD',
    roughness: 0.85,
    metalness: 0.0,
    finish: 'matte',
    description: 'Soft warm white with delicate linen undertones.',
    tag: 'Classic',
  },
  {
    id: 'wall-nordic-beige',
    name: 'Nordic Sand Beige',
    category: 'wall',
    type: 'color',
    color: '#D8CAB8',
    roughness: 0.85,
    metalness: 0.0,
    finish: 'matte',
    description: 'Earthy neutral tone inspired by natural stone and dune sands.',
  },
  {
    id: 'wall-concrete-grey',
    name: 'Mist Grey',
    category: 'wall',
    type: 'color',
    color: '#B0B2B5',
    roughness: 0.8,
    metalness: 0.02,
    finish: 'matte',
    description: 'Modern understated mid-tone grey with subtle warmth.',
  },
  {
    id: 'wall-charcoal',
    name: 'Anthracite Charcoal',
    category: 'wall',
    type: 'color',
    color: '#2B2D31',
    roughness: 0.75,
    metalness: 0.05,
    finish: 'matte',
    description: 'Bold, deep charcoal for dramatic architectural accent walls.',
    tag: 'Accent',
  },
  {
    id: 'wall-sage-green',
    name: 'Sage Mist Green',
    category: 'wall',
    type: 'color',
    color: '#8A9A86',
    roughness: 0.85,
    metalness: 0.0,
    finish: 'matte',
    description: 'Calming organic herbal green with muted grey tones.',
  },
  {
    id: 'wall-terracotta',
    name: 'Warm Tuscan Clay',
    category: 'wall',
    type: 'color',
    color: '#A95D44',
    roughness: 0.85,
    metalness: 0.0,
    finish: 'matte',
    description: 'Rich earthy terracotta for Mediterranean accents.',
  },
  {
    id: 'wall-architectural-navy',
    name: 'Midnight Architectural Blue',
    category: 'wall',
    type: 'color',
    color: '#1E293B',
    roughness: 0.75,
    metalness: 0.05,
    finish: 'matte',
    description: 'Deep sophisticated navy tailored for luxury interiors.',
  },

  // --- FLOOR MATERIALS ---
  {
    id: 'floor-oak-natural',
    name: 'Natural Scandinavian Oak',
    category: 'floor',
    type: 'texture',
    textureType: 'wood-oak',
    roughness: 0.35,
    metalness: 0.05,
    finish: 'satin',
    repeat: [3, 3],
    description: 'Engineered prime European oak with warm honey streaks.',
    tag: 'Bestseller',
  },
  {
    id: 'floor-walnut-dark',
    name: 'American Dark Walnut',
    category: 'floor',
    type: 'texture',
    textureType: 'wood-walnut',
    roughness: 0.3,
    metalness: 0.05,
    finish: 'satin',
    repeat: [3, 3],
    description: 'Rich cocoa-toned timber with expressive organic grain.',
  },
  {
    id: 'floor-herringbone',
    name: 'Herringbone Parquet Oak',
    category: 'floor',
    type: 'texture',
    textureType: 'wood-herringbone',
    roughness: 0.35,
    metalness: 0.05,
    finish: 'satin',
    repeat: [4, 4],
    description: 'Artisanal Parisian parquet pattern in bleached white oak.',
    tag: 'Luxury',
  },
  {
    id: 'floor-carrara-marble',
    name: 'Carrara Polished Marble',
    category: 'floor',
    type: 'texture',
    textureType: 'marble-carrara',
    roughness: 0.15,
    metalness: 0.1,
    finish: 'gloss',
    repeat: [2, 2],
    description: 'Iconic Italian white marble with soft smoke grey veining.',
    tag: 'Premium',
  },
  {
    id: 'floor-nero-marble',
    name: 'Nero Marquina Black Marble',
    category: 'floor',
    type: 'texture',
    textureType: 'marble-nero',
    roughness: 0.12,
    metalness: 0.15,
    finish: 'gloss',
    repeat: [2, 2],
    description: 'Deep obsidian black marble laced with delicate calcite veins.',
  },
  {
    id: 'floor-polished-concrete',
    name: 'Microcement Architectural Concrete',
    category: 'floor',
    type: 'texture',
    textureType: 'concrete-polished',
    roughness: 0.45,
    metalness: 0.05,
    finish: 'matte',
    repeat: [4, 4],
    description: 'Seamless industrial polished concrete with aggregate flecks.',
  },

  // --- BATHROOM & CERAMIC TILES ---
  {
    id: 'tile-white-subway',
    name: 'Glossy Metro Subway Tile',
    category: 'bathroom',
    type: 'texture',
    textureType: 'tile-subway',
    roughness: 0.18,
    metalness: 0.05,
    finish: 'gloss',
    repeat: [4, 4],
    description: 'Classic beveled brick subway ceramic with crisp grey grout.',
    tag: 'Essential',
  },
  {
    id: 'tile-grey-stone',
    name: 'Basalt Stone Paver Tiles',
    category: 'bathroom',
    type: 'texture',
    textureType: 'tile-stone',
    roughness: 0.6,
    metalness: 0.02,
    finish: 'textured',
    repeat: [3, 3],
    description: 'Honed architectural slate with non-slip tactile texture.',
  },
  {
    id: 'tile-travertine-stone',
    name: 'Roman Ivory Travertine',
    category: 'bathroom',
    type: 'texture',
    textureType: 'tile-travertine',
    roughness: 0.4,
    metalness: 0.05,
    finish: 'satin',
    repeat: [3, 3],
    description: 'Natural limestone with authentic horizontal pore banding.',
    tag: 'Trending',
  },
  {
    id: 'tile-pearl-terrazzo',
    name: 'Venetian Terrazzo Pearl',
    category: 'bathroom',
    type: 'texture',
    textureType: 'tile-terrazzo',
    roughness: 0.25,
    metalness: 0.08,
    finish: 'satin',
    repeat: [3, 3],
    description: 'Composite stone chips suspended in creamy off-white matrix.',
    tag: 'Artisanal',
  },
  {
    id: 'tile-emerald-glazed',
    name: 'Emerald Artisan Glazed Tile',
    category: 'bathroom',
    type: 'texture',
    textureType: 'tile-emerald',
    roughness: 0.15,
    metalness: 0.1,
    finish: 'gloss',
    repeat: [4, 4],
    description: 'Handcrafted Moroccan zellige-style lustrous green glaze.',
  },

  // --- ROOFING ---
  {
    id: 'roof-zinc-charcoal',
    name: 'Architectural Standing-Seam Zinc',
    category: 'roof',
    type: 'texture',
    textureType: 'zinc-roof',
    roughness: 0.4,
    metalness: 0.5,
    finish: 'satin',
    repeat: [3, 3],
    description: 'Contemporary standing seam titanium zinc with matte sheen.',
    tag: 'Modern',
  },
  {
    id: 'roof-terracotta-spanish',
    name: 'Spanish Barrel Terracotta Tile',
    category: 'roof',
    type: 'texture',
    textureType: 'terracotta-roof',
    roughness: 0.8,
    metalness: 0.05,
    finish: 'textured',
    repeat: [3, 3],
    description: 'Traditional curved clay roofing with rich earthen warmth.',
  },
  {
    id: 'roof-slate-black',
    name: 'Natural Charcoal Slate',
    category: 'roof',
    type: 'color',
    color: '#202224',
    roughness: 0.6,
    metalness: 0.1,
    finish: 'matte',
    description: 'Dark cleft roofing slate with minimalist elegance.',
  },

  // --- DOORS & FRAMES ---
  {
    id: 'door-teak-wood',
    name: 'Solid Burma Teak Wood',
    category: 'door',
    type: 'color',
    color: '#8A5632',
    roughness: 0.45,
    metalness: 0.05,
    finish: 'satin',
    description: 'Weather-resistant oiled teak with deep amber glow.',
  },
  {
    id: 'door-black-aluminum',
    name: 'Anodized Jet Black Aluminum',
    category: 'door',
    type: 'color',
    color: '#1A1A1A',
    roughness: 0.35,
    metalness: 0.85,
    finish: 'brushed',
    description: 'Sleek architectural powder-coated frame profile.',
    tag: 'Minimal',
  },
  {
    id: 'door-brushed-bronze',
    name: 'Architectural Brushed Bronze',
    category: 'door',
    type: 'color',
    color: '#6E553A',
    roughness: 0.35,
    metalness: 0.75,
    finish: 'brushed',
    description: 'Warm metallic finish with fine hairline brushing.',
  },
];

export function getMaterialsByCategory(category: MaterialCategory): MaterialOption[] {
  return MATERIAL_LIBRARY.filter((mat) => mat.category === category);
}

export function getMaterialById(id: string): MaterialOption | undefined {
  return MATERIAL_LIBRARY.find((mat) => mat.id === id);
}
